# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1182860216);
user_pref("app.update.lastUpdateTime.background-update-timer", 1182860216);
user_pref("browser.download.dir", "C:\\Documents and Settings\\Kristian\\Skrivebord");
user_pref("browser.download.progressDnldDialog.keepAlive", false);
user_pref("extensions.lastAppVersion", "1.5.0.12");
user_pref("intl.charsetmenu.mailview.cache", "UTF-8, windows-1252, windows-1258, ISO-8859-1, windows-1250");
user_pref("ldap_2.prefs_migrated", true);
user_pref("ldap_2.servers.default.filename", "default.mab");
user_pref("ldap_2.servers.default.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.default.uri", "moz-abldapdirectory://default.mab");
user_pref("ldap_2.servers.history.filename", "history.mab");
user_pref("ldap_2.servers.history.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.pab.filename", "abook.mab");
user_pref("ldap_2.servers.pab.replication.lastChangeNumber", 0);
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.identities", "id1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account2");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.compose.attach.dir", "D:\\Mine dokumenter m.m\\Anmeldelser\\PDF-filer af anmeldelser i HF");
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.doBccList", "");
user_pref("mail.identity.id1.draft_folder", "mailbox://nobody@Local%20Folders/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.encryption_cert_name", "");
user_pref("mail.identity.id1.encryptionpolicy", 0);
user_pref("mail.identity.id1.escapedVCard", "");
user_pref("mail.identity.id1.fcc_folder", "mailbox://nobody@Local%20Folders/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "Kristian Troelsen");
user_pref("mail.identity.id1.organization", "");
user_pref("mail.identity.id1.reply_on_top", 1);
user_pref("mail.identity.id1.reply_to", "");
user_pref("mail.identity.id1.sign_mail", false);
user_pref("mail.identity.id1.signing_cert_name", "");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "kst@mail.dk");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.compose.selectedTabIndex", 0);
user_pref("mail.root.none", "C:\\Documents and Settings\\Kristian\\Application Data\\Thunderbird\\Profiles\\sp6sum9n.default\\Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.root.pop3", "C:\\Documents and Settings\\Kristian\\Application Data\\Thunderbird\\Profiles\\sp6sum9n.default\\Mail");
user_pref("mail.root.pop3-rel", "[ProfD]Mail");
user_pref("mail.server.server1.ageLimit", 30);
user_pref("mail.server.server1.daysToKeepBodies", 30);
user_pref("mail.server.server1.daysToKeepHdrs", 30);
user_pref("mail.server.server1.directory", "C:\\Documents and Settings\\Kristian\\Application Data\\Thunderbird\\Profiles\\sp6sum9n.default\\Mail\\Local Folders");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.manualMark", true);
user_pref("mail.server.server1.moveOnSpam", true);
user_pref("mail.server.server1.name", "Lokale mapper");
user_pref("mail.server.server1.numHdrsToKeep", 30);
user_pref("mail.server.server1.serverFilterName", "SpamAssassin");
user_pref("mail.server.server1.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server1.spamActionTargetFolder", "mailbox://nobody@Local%20Folders/Junk");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server1.whiteListAbURI", "moz-abmdbdirectory://history.mab");
user_pref("mail.server.server2.ageLimit", 30);
user_pref("mail.server.server2.check_time", 5);
user_pref("mail.server.server2.daysToKeepBodies", 30);
user_pref("mail.server.server2.daysToKeepHdrs", 30);
user_pref("mail.server.server2.defer_get_new_mail", true);
user_pref("mail.server.server2.deferred_to_account", "account1");
user_pref("mail.server.server2.delete_by_age_from_server", true);
user_pref("mail.server.server2.delete_mail_left_on_server", true);
user_pref("mail.server.server2.directory", "C:\\Documents and Settings\\Kristian\\Application Data\\Thunderbird\\Profiles\\sp6sum9n.default\\Mail\\pop3.mail.dk");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/pop3.mail.dk");
user_pref("mail.server.server2.download_on_biff", true);
user_pref("mail.server.server2.hostname", "pop3.mail.dk");
user_pref("mail.server.server2.login_at_startup", true);
user_pref("mail.server.server2.name", "kst@mail.dk");
user_pref("mail.server.server2.numHdrsToKeep", 30);
user_pref("mail.server.server2.type", "pop3");
user_pref("mail.server.server2.userName", "120011901315");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "asmtp.mail.dk");
user_pref("mail.smtpserver.smtp1.username", "120011901315");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.spellcheck.inline", false);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.ui.junk.firstuse", false);
user_pref("mailnews.ui.threadpane.version", 5);
user_pref("messenger.save.dir", "C:\\Documents and Settings\\Kristian\\Skrivebord");
user_pref("spellchecker.dictionary", "da");
user_pref("wallet.caveat", true);
